### ISSUE TITLE
建议：将实现代码放在.cpp文件中

### ISSUE THREAD

**Issue by ice1000** [Heptagon196/Snake#1]
我看到你的大部分业务代码都在Snaker.h里面，然而标准是声明放头文件 实现放cpp文件的 要不你把它分离一下 然后改一下makefile 😂

**Comment by Heptagon196** [comment]
### 你妹的强迫症。
这是初二写的程序，初三重构了一次。初二的代码更是一坨**
当时毛都不懂，而且大括号单独写一行。
而且我已经弃坑了，还有无数个BUG没修复。
而且我现在也没解决怎么把实现放cpp……怎么试都是重复定义。

**Comment by ice1000** [comment]
还有 我拉你加CDFLS组织了

**Comment by Heptagon196** [comment]
### 你妹的强迫症。
这是初二写的程序，初三重构了一次。初二的代码更是一坨**
当时毛都不懂，而且大括号单独写一行。
而且我已经弃坑了，还有无数个BUG没修复。
而且我现在也没解决怎么把实现放cpp……怎么试都是重复定义。
(这是初二的程序，其实比这个好玩:http://7xktdn.com1.z0.glb.clouddn.com/Snake.zip)

**Comment by ice1000** [comment]
%%%%%%%%%%%%%%%%%%%
![](http://imgsrc.baidu.com/forum/w%3D580/sign=451438abc4cec3fd8b3ea77de688d4b6/0b00f45d1038534307f442469413b07eca80884e.jpg)
